Query.Mode=0;
Query.Platform.ID="BB-PlayBook";
Query.Platform.Mobile=true;
Query.Platform.AddressProxy=false;
Query.Platform.PageSize=25;//poor pb browser can't keep up sometimes...
//don't want to hard-embed the search fields because they contain lots of dynamic data, this datafile is generated by prep.bat from the live site

$(document).ready(function(){
	
	Query.FloatingSearchFields=false;
	$.get("proj_query.html",function(contents){
		//and this is where I hack everything up!
		$("#searchFields").html(contents+$("#searchFields").html());
		$(".fieldGroup:not(.right)").append($("#searchTips"));
		//sorrry districtsfrancophonesdunouveaubrunswickdfnb, your name is breaking the layout
		$("option[value='districtsfrancophonesdunouveaubrunswickdfnb']").text("DFNB");
		
		/* this was supposed to make the BB OSK show "search" instead of "enter" but oh well
		$("#searchFields input[type='text']").each(function(){
			this.type="search";
			$(this).css("-webkit-appearance","textField");
		});*/

		$(".fieldGroup.right fieldset").append($("<div class=\"fieldGroupDivider\">"));
		$(".fieldGroup.right table").first().append($(".fieldGroup.right tr"));
		$("#bodyWrap").css("bottom",($("#footer").outerHeight())+"px");
		setTimeout(Query.Init,10);
		$("input").focus(function(){
			$("#footer").hide();
		});
		Query.onPopulate=function(){
			hideSplash();
		}
	});
	$("#searchFields").get(0).addEventListener('touchmove', function(e){ e.preventDefault(); });
	//Query.iScroll = new iScroll('bodyWrap',{fadeScrollbar:true,hideScrollbar:true});

	var resTable=$("#resultsTable");
	var searchFields=$("#searchFields");

	//fix links in result section
	$('body').on({
		click:function(){
			if ($(this).attr("href").length!==0 && $(this).attr("href")!="#"){
				var args = new blackberry.invoke.BrowserArguments($(this).attr("href"));
				blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, args);
			}
		}
	},'a');

	$("#resultsTable").on({
		touchmove:function(e){
			e.preventDefault();
		}
	},'div.insightButton , div.refineButton');

	blackberry.app.event.onSwipeDown(function(){
		//$("html:not(:animated),body:not(:animated)").animate({ scrollTop: 0}, 500 );
		//$(searchFields).animate({"top":"0px"});
		//searchFields.removeClass("collapsed");
		if ($("body").scrollTop()<searchFields.outerHeight()){
			$("html:not(:animated),body:not(:animated)").animate({ scrollTop: 0}, 500 );
		} else {
			if (!Query.FloatedSearchFields){
				Query.FloatSearchFields();
			} else {
				Query.UnfloatSearchFields();
			}
		}
		
	});
	
	$(window).resize(function(){
		//show/hide footer based on virt. keyboard
		if ($(window).height()<500){
			$("#footer").hide();
		} else {
			$("#footer").show();
		}
	});
	$(document).scroll(function(){
		if ($(document).scrollTop()===0){
			Query.UnfloatSearchFields(false);
		}
	});
});

function hideSplash(){
	$("#bodyWrap, #footer").css("visibility","visible");
	$("#splash").hide();
	$("html").css("background-color", "#eaeaea");
	$("body").css("overflow-y","auto");

}

Query.FloatSearchFields=function(){
	if (Query.FloatedSearchFields) return;
	Query.FloatedSearchFields=true;
	setTimeout(function(){
		$("#searchFields").css('-webkit-transition', 'all 0.5s ease-in-out');
		$("#searchFields").css('-webkit-transform','translate(0, '+$("#searchFields").outerHeight()+'px)');
	},0);
	$("#searchFields").css({"position":"fixed","top":"-"+$("#searchFields").outerHeight()+"px"});
	$("#resultsTable").css({"padding-top":$("#searchFields").outerHeight()+"px"});
};

Query.UnfloatSearchFields=function(noAnim){
	if (!Query.FloatedSearchFields) return;
	Query.FloatedSearchFields=false;
	if (noAnim===false){
		$("#searchFields").css({"position":"relative","top":"auto"});
		$("#resultsTable").css({"padding-top":"0px"});
		$("#searchFields").css('-webkit-transition', 'none');
		$("#searchFields").css('-webkit-transform','translate(0, 0)');
	} else {
		$("#searchFields").css('-webkit-transition', 'all 0.5s ease-in-out');
		$("#searchFields").css('-webkit-transform','translate(0, 0)');
		setTimeout(function(){
			$("#searchFields").css('-webkit-transition', 'none');
			$("#searchFields").css({"position":"relative","top":"auto"});
			$("#resultsTable").css({"padding-top":"0px"});
		},500);
	}
	
};

Query.onQuery=function(){
	$("#resultsTable .loadingWrap").show();
};

Query.beforePopulate=function(){
	$("#resultsTable .loadingWrap").hide();
};

//matches the hackiness of the rest of the insight system...
Insight.ShowCallback=function(content){
	$(".insightDiag").html(content);
	$(".insightDiag img").each(function(){
		$(this).attr("src","http://cwsf.cpfx.ca/"+$(this).attr("src"));
	});
	$(".insightDiag").css("top",$(window).scrollTop()+$(window).height()*0.1);
};

$.ajaxSetup({
        scriptCharset: "UTF-8",
        cache: false
});